export const mockUserData = {
  name: '이한별',
  introduction:
    '안녕하세요 디자이너 이한별입니다. 저는 지금 배가 고파요. 전자정보도서관에서 모각작 하실 분 모집합니다. 우하하 우하하',
  kakaoTalkId: 'hanbyeol1234',
  mbti: 'ENTJ',
  profileImage: '@/assets/images/ic_logo.png',
  cardinal: 5,
  position: 'D',
};

export interface LeenkDataType {
  id: string;
  isWrite?: boolean;
  title: string;
  date: string;
  people: string;
  name: string;
  leenkImageUri: null;
  profileImageUri: null;
  kakaoTalkId?: string;
}

export const mockLeenkData = [
  {
    id: '1',
    title: '전정도에서 모두모여잉전정도에서 모두모여잉전정도에서 모두',
    date: '12월 28일 22시',
    people: '3/20명',
    name: '김링크',
    leenkImageUri: null,
    profileImageUri: null,
    cotent:
      '저희 전정도 스터디룸 빌리려는데 2명 이상 모집해요오오오오오오오 일단 2명 빠르게 구하고 더 오실 분들은 참여해주세용!! 1시까지 바로 올 수 있으신 분들 꼭 와주시면 넘 좋겠어요... 다들 친해지고 싶어요! 누구든 오셔서 같이 작업해용!',
    participantCount: 3,
    allParticipants: 20,
    place: '전정도 B1 룸 A',
    createdAt: '2025-06-30T00:00:00',
    isWrite: true,
    kakaoTalkId: 'kakao0001',
  },
  {
    id: '2',
    title: 'Title 2',
    date: '12월 02일 04시',
    people: '2/20명',
    name: '이름2',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 2에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 2,
    allParticipants: 20,
    place: '전정도 B1 룸 B',
    createdAt: '2025-06-02T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0002',
  },
  {
    id: '3',
    title: 'Title 3',
    date: '12월 03일 06시',
    people: '3/20명',
    name: '이름3',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 3에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 3,
    allParticipants: 20,
    place: '전정도 B1 룸 C',
    createdAt: '2025-06-03T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0003',
  },
  {
    id: '4',
    title: 'Title 4',
    date: '12월 04일 08시',
    people: '4/20명',
    name: '이름4',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 4에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 4,
    allParticipants: 20,
    place: '전정도 B1 룸 D',
    createdAt: '2025-06-04T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0004',
  },
  {
    id: '5',
    title: 'Title 5',
    date: '12월 05일 10시',
    people: '5/20명',
    name: '이름5',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 5에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 5,
    allParticipants: 20,
    place: '전정도 B1 룸 E',
    createdAt: '2025-06-05T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0005',
  },
  {
    id: '6',
    title: 'Title 6',
    date: '12월 06일 12시',
    people: '6/20명',
    name: '이름6',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 6에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 6,
    allParticipants: 20,
    place: '전정도 B1 룸 F',
    createdAt: '2025-06-06T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0006',
  },
  {
    id: '7',
    title: 'Title 7',
    date: '12월 07일 14시',
    people: '7/20명',
    name: '이름7',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 7에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 7,
    allParticipants: 20,
    place: '전정도 B1 룸 G',
    createdAt: '2025-06-07T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0007',
  },
  {
    id: '8',
    title: 'Title 8',
    date: '12월 08일 16시',
    people: '8/20명',
    name: '이름8',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 8에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 8,
    allParticipants: 20,
    place: '전정도 B1 룸 H',
    createdAt: '2025-06-08T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0008',
  },
  {
    id: '9',
    title: 'Title 9',
    date: '12월 09일 18시',
    people: '9/20명',
    name: '이름9',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 9에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 9,
    allParticipants: 20,
    place: '전정도 B1 룸 I',
    createdAt: '2025-06-09T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0009',
  },
  {
    id: '10',
    title: 'Title 10',
    date: '12월 10일 20시',
    people: '1/20명',
    name: '이름10',
    leenkImageUri: null,
    profileImageUri: null,
    cotent: 'Title 10에 대한 설명입니다. 함께할 분을 모집해요!',
    participantCount: 1,
    allParticipants: 20,
    place: '전정도 B1 룸 J',
    createdAt: '2025-06-10T00:00:00',
    isWrite: false,
    kakaoTalkId: 'kakao0010',
  },
];
