export const mockUserData = {
  name: '이한별',
  introduction:
    '안녕하세요 디자이너 이한별입니다. 저는 지금 배가 고파요. 전자정보도서관에서 모각작 하실 분 모집합니다. 우하하 우하하',
  kakaoTalkId: 'hanbyeol1234',
  mbti: 'ENTJ',
  profileImage: '@/assets/images/ic_logo.png',
  cardinal: 5,
  position: 'D',
};

export interface LeenkDataType {
  id: string;
  isWrite?: boolean;
  title: string;
  date: string;
  people: string;
  name: string;
  leenkImageUri: null;
  profileImageUri: null;
  kakaoTalkId: string;
}

export const mockLeenkData = [
  {
    id: '1',
    title: '전정도에서 모두모여잉',
    date: '12월 28일 22시',
    people: '3/20명',
    name: '김링크',
    leenkImageUri: null,
    profileImageUri: null,
    cotent:
      '저희 전정도 스터디룸 빌리려는데 2명 이상 모집해요오오오오오오오 일단 2명 빠르게 구하고 더 오실 분들은 참여해주세용!! 1시까지 바로 올 수 있으신 분들 꼭 와주시면 넘 좋겠어요... 다들 친해지고 싶어요! 누구든 오셔서 같이 작업해용!',
    participantCount: 3,
    allParticipants: 20,
    place: '전정도 B1 룸 A',
    createdAt: '2025-06-30T00:00:00',
    isWrite: true,
    kakaoTalkId: 'hanbyeol1234',
  },
  {
    id: '2',
    title: '카공 할 사람 급구',
    date: '12월 02일 15시',
    people: '1/20명',
    name: '이유진',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'hansda34',
  },
  {
    id: '3',
    title: '볼링 모임 ㄱ',
    date: '11월 30일 19시',
    people: '6/20명',
    name: '계다현',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'hawwr3434',
  },
  {
    id: '4',
    title: '같이 점심 먹장',
    date: '12월 18일 11시',
    people: '3/20명',
    name: '김윙크',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'asdad234',
  },
  {
    id: '5',
    title: '야식 같이 먹을 사람~',
    date: '12월 01일 23시',
    people: '4/10명',
    name: '박찬호',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: '134fsfl4',
  },
  {
    id: '6',
    title: '방탈출 같이 가실 분?',
    date: '12월 09일 17시',
    people: '2/6명',
    name: '정지훈',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'aafsk234',
  },
  {
    id: '7',
    title: '새내기 환영회 준비 모임',
    date: '12월 05일 20시',
    people: '5/15명',
    name: '홍길동',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'afs004',
  },
  {
    id: '8',
    title: '동아리 MT 기획 회의',
    date: '12월 07일 18시',
    people: '8/10명',
    name: '이민지',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'asdq11234',
  },
  {
    id: '9',
    title: '연말 파티 기획팀 모집',
    date: '12월 21일 19시',
    people: '3/5명',
    name: '최유정',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: '1ad1234',
  },
  {
    id: '10',
    title: '조별과제 만나서 하실 분',
    date: '12월 04일 14시',
    people: '2/4명',
    name: '한지성',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'aaol1234',
  },
  {
    id: '11',
    title: '테니스 치실 분 구해요!',
    date: '12월 13일 16시',
    people: '1/2명',
    name: '오승민',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'byeol1234',
  },
  {
    id: '12',
    title: '독서 모임 시즌2 모집',
    date: '12월 10일 20시',
    people: '7/12명',
    name: '서지후',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'as1234',
  },
  {
    id: '13',
    title: '사진 찍으러 나들이~',
    date: '12월 17일 10시',
    people: '5/8명',
    name: '장유나',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'yunas2',
  },
  {
    id: '14',
    title: '카페인 중독자 모임',
    date: '12월 03일 09시',
    people: '6/6명',
    name: '윤서빈',
    leenkImageUri: null,
    profileImageUri: null,
    kakaoTalkId: 'ssk1',
  },
];
